export const TAG_TAXONOMY_VERSION = "qeo-tags-v1";
export const TAG_MIN_SCORE = 0.04;
export const TAG_MAX_AI_TAGS = 5;

export interface TagVocabularyEntry {
  slug: string;
  name: string;
  prompt: string;
}

export const TAG_VOCABULARY: readonly TagVocabularyEntry[] = [
  { slug: "screenshot", name: "Screenshot", prompt: "a screenshot from a phone, tablet, or computer" },
  { slug: "document", name: "Document", prompt: "a photographed or scanned document" },
  { slug: "receipt", name: "Receipt", prompt: "a purchase receipt or payment receipt" },
  { slug: "invoice", name: "Invoice", prompt: "an invoice or billing document" },
  { slug: "menu", name: "Menu", prompt: "a restaurant, cafe, or food menu" },
  { slug: "text", name: "Text", prompt: "an image dominated by readable text" },
  { slug: "handwriting", name: "Handwriting", prompt: "handwritten notes or handwritten text" },
  { slug: "whiteboard", name: "Whiteboard", prompt: "a whiteboard with notes or drawings" },
  { slug: "presentation", name: "Presentation", prompt: "a presentation slide or projected slide" },
  { slug: "diagram", name: "Diagram", prompt: "a diagram, flowchart, or schematic" },
  { slug: "chart", name: "Chart", prompt: "a chart, graph, or plotted visualization" },
  { slug: "spreadsheet", name: "Spreadsheet", prompt: "a spreadsheet or table of data" },
  { slug: "qr-code", name: "QR Code", prompt: "a visible QR code" },
  { slug: "barcode", name: "Barcode", prompt: "a visible product barcode" },
  { slug: "book", name: "Book", prompt: "a book, book cover, or book page" },
  { slug: "ticket", name: "Ticket", prompt: "a ticket, pass, or boarding pass" },
  { slug: "family", name: "Family", prompt: "a family photo with family members" },
  { slug: "baby", name: "Baby", prompt: "a baby or infant" },
  { slug: "child", name: "Child", prompt: "a child or young kid" },
  { slug: "couple", name: "Couple", prompt: "a couple posing or spending time together" },
  { slug: "group", name: "Group", prompt: "a group of people posing together" },
  { slug: "friends", name: "Friends", prompt: "friends socializing or posing together" },
  { slug: "portrait", name: "Portrait", prompt: "a portrait focused on one person" },
  { slug: "selfie", name: "Selfie", prompt: "a selfie taken at arm's length" },
  { slug: "wedding", name: "Wedding", prompt: "a wedding ceremony, bride, groom, or wedding party" },
  { slug: "birthday", name: "Birthday", prompt: "a birthday celebration, cake, or birthday party" },
  { slug: "party", name: "Party", prompt: "a social party or celebration" },
  { slug: "graduation", name: "Graduation", prompt: "a graduation ceremony, gown, or diploma" },
  { slug: "pet", name: "Pet", prompt: "a household pet or companion animal" },
  { slug: "crowd", name: "Crowd", prompt: "a large crowd of people" },
  { slug: "dog", name: "Dog", prompt: "a dog" },
  { slug: "cat", name: "Cat", prompt: "a cat" },
  { slug: "car", name: "Car", prompt: "a car or automobile" },
  { slug: "motorcycle", name: "Motorcycle", prompt: "a motorcycle or motorbike" },
  { slug: "bicycle", name: "Bicycle", prompt: "a bicycle or bike" },
  { slug: "computer", name: "Computer", prompt: "a desktop computer or computer workstation" },
  { slug: "laptop", name: "Laptop", prompt: "a laptop computer" },
  { slug: "phone", name: "Phone", prompt: "a mobile phone or smartphone" },
  { slug: "tablet", name: "Tablet", prompt: "a tablet computer or iPad" },
  { slug: "television", name: "Television", prompt: "a television or TV screen" },
  { slug: "camera", name: "Camera", prompt: "a camera or camera equipment" },
  { slug: "food", name: "Food", prompt: "prepared food, a meal, or a dish" },
  { slug: "drink", name: "Drink", prompt: "a beverage or drink" },
  { slug: "coffee", name: "Coffee", prompt: "coffee, a coffee cup, or a coffee drink" },
  { slug: "product", name: "Product", prompt: "a product photographed for reference or shopping" },
  { slug: "package", name: "Package", prompt: "a parcel, package, or shipping box" },
  { slug: "clothing", name: "Clothing", prompt: "clothes, apparel, or an outfit" },
  { slug: "furniture", name: "Furniture", prompt: "furniture such as a chair, table, sofa, or cabinet" },
  { slug: "home", name: "Home", prompt: "a home, apartment, or domestic living space" },
  { slug: "office", name: "Office", prompt: "an office or workplace" },
  { slug: "indoor", name: "Indoor", prompt: "an indoor scene inside a building" },
  { slug: "outdoor", name: "Outdoor", prompt: "an outdoor scene in open air" },
  { slug: "beach", name: "Beach", prompt: "a beach, shoreline, or seaside scene" },
  { slug: "city", name: "City", prompt: "a city or urban skyline" },
  { slug: "street", name: "Street", prompt: "a street, road, or urban sidewalk" },
  { slug: "building", name: "Building", prompt: "a building or architectural exterior" },
  { slug: "nature", name: "Nature", prompt: "a natural landscape or nature scene" },
  { slug: "mountain", name: "Mountain", prompt: "a mountain or mountainous landscape" },
  { slug: "forest", name: "Forest", prompt: "a forest, woods, or dense trees" },
  { slug: "sky", name: "Sky", prompt: "the sky as a prominent subject" },
  { slug: "sunset", name: "Sunset", prompt: "a sunset or colorful evening sky" },
  { slug: "travel", name: "Travel", prompt: "a travel or vacation scene" },
  { slug: "hotel", name: "Hotel", prompt: "a hotel, resort, or hotel room" },
  { slug: "airport", name: "Airport", prompt: "an airport terminal or airport scene" },
  { slug: "airplane", name: "Airplane", prompt: "an airplane or aircraft" },
  { slug: "train", name: "Train", prompt: "a train, railway carriage, or locomotive" },
  { slug: "bus", name: "Bus", prompt: "a bus or coach" },
  { slug: "boat", name: "Boat", prompt: "a boat, ship, or watercraft" },
  { slug: "event", name: "Event", prompt: "an organized public or private event" },
  { slug: "concert", name: "Concert", prompt: "a live concert, stage, or music performance" },
  { slug: "sports", name: "Sports", prompt: "a sports game, match, or athletic competition" },
  { slug: "fitness", name: "Fitness", prompt: "exercise, fitness training, or a gym workout" },
  { slug: "chat", name: "Chat", prompt: "a screenshot of a chat or messaging conversation" },
  { slug: "social-media", name: "Social Media", prompt: "a screenshot of a social media post or feed" },
  { slug: "meme", name: "Meme", prompt: "an internet meme or humorous captioned image" },
  { slug: "map", name: "Map", prompt: "a map, navigation view, or geographic map" },
  { slug: "sign", name: "Sign", prompt: "a sign, notice, or posted instruction" },
  { slug: "logo", name: "Logo", prompt: "a brand logo or emblem" },
  { slug: "art", name: "Art", prompt: "artwork, painting, illustration, or sculpture" },
  { slug: "design", name: "Design", prompt: "a graphic design, layout, or visual design work" },
] as const;
