export const TAG_TAXONOMY_VERSION = "qeo-tags-v1";
export const TAG_MIN_SCORE = 0.04;
export const TAG_MAX_AI_TAGS = 5;

export interface TagVocabularyEntry {
  slug: string;
  name: string;
  prompt: string;
}

export const TAG_VOCABULARY: readonly TagVocabularyEntry[] = [
  { slug: "screenshot", name: "Screenshot", prompt: "a screenshot" },
  { slug: "document", name: "Document", prompt: "a document" },
  { slug: "receipt", name: "Receipt", prompt: "a receipt" },
  { slug: "invoice", name: "Invoice", prompt: "an invoice" },
  { slug: "menu", name: "Menu", prompt: "a food menu" },
  { slug: "text", name: "Text", prompt: "an image of text" },
  { slug: "handwriting", name: "Handwriting", prompt: "handwritten text" },
  { slug: "whiteboard", name: "Whiteboard", prompt: "a whiteboard" },
  { slug: "presentation", name: "Presentation", prompt: "a presentation slide" },
  { slug: "diagram", name: "Diagram", prompt: "a diagram" },
  { slug: "chart", name: "Chart", prompt: "a chart" },
  { slug: "spreadsheet", name: "Spreadsheet", prompt: "a spreadsheet" },
  { slug: "qr-code", name: "QR Code", prompt: "a QR code" },
  { slug: "barcode", name: "Barcode", prompt: "a barcode" },
  { slug: "book", name: "Book", prompt: "a book" },
  { slug: "ticket", name: "Ticket", prompt: "a ticket" },
  { slug: "family", name: "Family", prompt: "a family photo" },
  { slug: "baby", name: "Baby", prompt: "a baby" },
  { slug: "child", name: "Child", prompt: "a child" },
  { slug: "couple", name: "Couple", prompt: "a couple" },
  { slug: "group", name: "Group", prompt: "a group of people" },
  { slug: "friends", name: "Friends", prompt: "friends together" },
  { slug: "portrait", name: "Portrait", prompt: "a portrait" },
  { slug: "selfie", name: "Selfie", prompt: "a selfie" },
  { slug: "wedding", name: "Wedding", prompt: "a wedding" },
  { slug: "birthday", name: "Birthday", prompt: "a birthday" },
  { slug: "party", name: "Party", prompt: "a party" },
  { slug: "graduation", name: "Graduation", prompt: "a graduation" },
  { slug: "pet", name: "Pet", prompt: "a pet" },
  { slug: "crowd", name: "Crowd", prompt: "a crowd" },
  { slug: "dog", name: "Dog", prompt: "a dog" },
  { slug: "cat", name: "Cat", prompt: "a cat" },
  { slug: "car", name: "Car", prompt: "a car" },
  { slug: "motorcycle", name: "Motorcycle", prompt: "a motorcycle" },
  { slug: "bicycle", name: "Bicycle", prompt: "a bicycle" },
  { slug: "computer", name: "Computer", prompt: "a desktop computer" },
  { slug: "laptop", name: "Laptop", prompt: "a laptop" },
  { slug: "phone", name: "Phone", prompt: "a phone" },
  { slug: "tablet", name: "Tablet", prompt: "a tablet" },
  { slug: "television", name: "Television", prompt: "a television" },
  { slug: "camera", name: "Camera", prompt: "a camera" },
  { slug: "food", name: "Food", prompt: "food" },
  { slug: "drink", name: "Drink", prompt: "a drink" },
  { slug: "coffee", name: "Coffee", prompt: "coffee" },
  { slug: "product", name: "Product", prompt: "a product" },
  { slug: "package", name: "Package", prompt: "a package" },
  { slug: "clothing", name: "Clothing", prompt: "clothing" },
  { slug: "furniture", name: "Furniture", prompt: "furniture" },
  { slug: "home", name: "Home", prompt: "a home interior" },
  { slug: "office", name: "Office", prompt: "an office" },
  { slug: "indoor", name: "Indoor", prompt: "an indoor scene" },
  { slug: "outdoor", name: "Outdoor", prompt: "an outdoor scene" },
  { slug: "beach", name: "Beach", prompt: "a beach" },
  { slug: "city", name: "City", prompt: "a city" },
  { slug: "street", name: "Street", prompt: "a city street" },
  { slug: "building", name: "Building", prompt: "a building" },
  { slug: "nature", name: "Nature", prompt: "a nature scene" },
  { slug: "mountain", name: "Mountain", prompt: "a mountain" },
  { slug: "forest", name: "Forest", prompt: "a forest" },
  { slug: "sky", name: "Sky", prompt: "the sky" },
  { slug: "sunset", name: "Sunset", prompt: "a sunset" },
  { slug: "travel", name: "Travel", prompt: "a travel photo" },
  { slug: "hotel", name: "Hotel", prompt: "a hotel" },
  { slug: "airport", name: "Airport", prompt: "an airport" },
  { slug: "airplane", name: "Airplane", prompt: "an airplane" },
  { slug: "train", name: "Train", prompt: "a train" },
  { slug: "bus", name: "Bus", prompt: "a bus" },
  { slug: "boat", name: "Boat", prompt: "a boat" },
  { slug: "event", name: "Event", prompt: "an event" },
  { slug: "concert", name: "Concert", prompt: "a concert" },
  { slug: "sports", name: "Sports", prompt: "a sports event" },
  { slug: "fitness", name: "Fitness", prompt: "a fitness activity" },
  { slug: "chat", name: "Chat", prompt: "a chat conversation" },
  { slug: "social-media", name: "Social Media", prompt: "a social media post" },
  { slug: "meme", name: "Meme", prompt: "a meme" },
  { slug: "map", name: "Map", prompt: "a map" },
  { slug: "sign", name: "Sign", prompt: "a sign" },
  { slug: "logo", name: "Logo", prompt: "a logo" },
  { slug: "art", name: "Art", prompt: "artwork" },
  { slug: "design", name: "Design", prompt: "a graphic design" },
] as const;
